rust-playpen-error (#192)
* Version 0.2.3 of mdbook works fine for "mdbook build && mdbook test"
Version 0.3.0 of mdbook breaks for "mdbook build && mdbook test"
Version ^0.1 of mdbook breaks for "mdbook build && mdbook test"

```
error[E0463]: can't find crate for `secp256k1`
 --> cryptography/digital_signatures/introduction_schnorr_signatures.md
  |
2 | extern crate libsecp256k1_rs as secp256k1;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```

* The previous attempt did not fix the Travis error. Trying to do `mdbook build` only without `mdbook test`